[project]
name = "langchain-course"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4>=4.14.3",
    "black==26.1.0",
    "faiss-cpu>=1.13.2",
    "isort>=7.0.0",
    "langchain==1.2.6",
    "langchain-community>=0.4.1",
    "langchain-experimental>=0.4.1",
    "langchain-openai>=1.1.7",
    "langchain-pinecone>=0.2.13",
    "langchain-tavily==0.2.17",
    "langchainhub>=0.1.21",
    "langsmith==0.6.4",
    "pypdf>=6.6.0",
    "python-dotenv>=1.2.1",
    "qrcode>=8.2",
    "streamlit>=1.53.1",
    "tavily-python>=0.7.19",
]
